### ISSUE TITLE
Syntax highlighting in text selection too?

### ISSUE THREAD

**Issue by circuuz** [oivva/otto#18]
Is it possible to not "disable" the syntax highlighting when selecting text?

**Comment by oivva** [comment]
Thanks for reporting the issue. I agree, selection without disabling the syntax highlighting will be much better. I'll fix it in the next patch (will be released on 05 March).
P.S. If you want to do this manually until the next version - look at https://github.com/oivva/otto#even-more and remove:

```xml
<key>selectionForeground</key>
<string>#a7adba</string>
```

e.g. from https://github.com/oivva/otto/blob/master/schemes/Otto%20Oceanic.tmTheme

**Comment by circuuz** [comment]
Thanks alot!

**Comment by oivva** [comment]
You're welcome 😉
