### ISSUE TITLE
Add font size settings

### ISSUE THREAD

**Issue by smlombardi** [oivva/otto#19]
My old eyes can barely read some of it on the Thunderbolt display.

I can adjust it with package resource viewer, I found the find/replace text, but where can I control the font for the sidebar items?  I'd like to change the face and size.

Thanks.

**Comment by oivva** [comment]
Thanks for reporting the issue. I have plans to add font settings in the next release. If you want to do this manually until the next version - look at [Sublime Text Sidebar Font Settings](http://superuser.com/questions/748381/sublime-text-3-sidebar-font-face-change)

**Comment by smlombardi** [comment]
Thanks
