### ISSUE TITLE
Tab separators

### ISSUE THREAD

**Issue by gj1118** [oivva/otto#20]
Can you please add a configuration setting for removing/disabling the tab separator line in the "Yesterday" theme. 

In the tommorow theme , it mingles with the theme, and hence does not stand out, but with the light theme , it stands out a bit. Having a configuration setting, should resolve it for people who would love to keep it and also for people like me. 

Excellent Job! Congratulations.

Thanks and Regards
Gagan

![image](https://cloud.githubusercontent.com/assets/473101/13507013/c0918fa2-e14e-11e5-9632-f98fbf2bcb4f.png)

**Comment by oivva** [comment]
I agree, I'll add a configuration setting in the next release.
