### ISSUE TITLE
es6 class method text is unvisible with Tomorrow theme

### ISSUE THREAD

**Issue by xyzlast** [oivva/otto#21]
This is javascript code with es6 syntax. It's to difficult to see the method of classes. 

![tomorrow-theme](https://cloud.githubusercontent.com/assets/3388377/13518215/eccccbf2-e20e-11e5-8ab0-cc0db2c2e20b.jpg)

**Comment by oivva** [comment]
Thanks for reporting the issue. I'll fix it in the next release.

**Comment by xyzlast** [comment]
Thank you @oivva . It's wonderful theme I known.

**Comment by oivva** [comment]
You're welcome 😉
