### ISSUE TITLE
Lots of icons broken..

### ISSUE THREAD

**Issue by circuuz** [oivva/otto#28]
![screen shot 2016-03-11 at 08 02 47](https://cloud.githubusercontent.com/assets/640695/13695508/c55d8272-e75f-11e5-8f12-688c0e1cb6b4.png)

**Comment by circuuz** [comment]
@oivva Please fix or give me a way to fix it :)

**Comment by oivva** [comment]
@circuuz Ok:) Possible solutions:

1. Try to restart Sublime Text: **`Sublime Text -> Quit`** or to force quit, hold the Option key on your keyboard while you right-click on the app’s Dock icon and you’ll see that “Quit” is now “Force Quit.” Click it to force quit the app.

2. Go to **`Sublime Text -> Preferences -> Browse Packages ...`** and remove `Theme - Otto` directory if it exists, then repeat step 1.

**Comment by circuuz** [comment]
@oivva The second one solved it, thanks alot!
